### ISSUE TITLE
FATAL ERROR: Could not complete note + interval operation: D5## + aug2

### ISSUE THREAD

**Issue by mungewell** [charlottepierce/music_essentials#1]
Discovered when attempting to implement Pentatonic scales...

```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from music_essentials import Scale,Note,Interval
>>> a = Note.from_note_string('D5##')
>>> a + Interval('aug', 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\music_essentials\note.py", line 338, in __add__
    raise RuntimeError('FATAL ERROR: Could not complete note + interval operation: ' + str(self) + ' + ' + str(other))
RuntimeError: FATAL ERROR: Could not complete note + interval operation: D5## + aug2
>>>
```

**Comment by mungewell** [comment]
New Def's
```
    _MAJOR_PENTATONIC = (_TONE, _TONE, _TONE_AND_HALF, _TONE, _TONE_AND_HALF)
    _MINOR_PENTATONIC = (_TONE_AND_HALF, _TONE, _TONE, _TONE_AND_HALF, _TONE)

```

Example code attached. 
[test.py.txt](https://github.com/charlottepierce/music_essentials/files/2113588/test.py.txt)

```
('minor pentatonic', 'A4')
['B4#']
['B4#', 'C5##']
['B4#', 'C5##', 'D5##']
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    new = scale[-1] + diff
  File "build\bdist.win32\egg\music_essentials\note.py", line 338, in __add__
    raise RuntimeError('FATAL ERROR: Could not complete note + interval operation: ' + str(self) + ' + ' + str(other))
RuntimeError: FATAL ERROR: Could not complete note + interval operation: D5## + aug2
```

**Comment by mungewell** [comment]
Root problem (building Pentatonic Scale) fixed in:
https://github.com/charlottepierce/music_essentials/pull/3

Happy for you to say "won't fix" for the standalone example - it may be nonsensical afterall....
