### ISSUE TITLE
TypeError: Expected integer for octave, got 3.0

### ISSUE THREAD

**Issue by mungewell** [charlottepierce/music_essentials#2]
FaIls with Python2, but works with Python3

```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from music_essentials import Note
>>> Note.from_midi_num(56)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build\bdist.win32\egg\music_essentials\note.py", line 188, in from_midi_num
    return cls(pitch, octave, accidental)
  File "build\bdist.win32\egg\music_essentials\note.py", line 67, in __init__
    raise TypeError('Expected integer for octave, got ' + str(octave))
TypeError: Expected integer for octave, got 3.0
```

**Comment by mungewell** [comment]
fixed in
https://github.com/charlottepierce/music_essentials/pull/3
